apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: ai-task-platform
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://username:password@cluster.mongodb.net/ai-task-platform"
  JWT_SECRET: "change-this-to-a-long-random-string"
